export const GET_POPULAR_MOVIES = 'mdb/GET_POPULAR_MOVIES';
export const GET_POPULAR_MEDIAS_SUCCEED = 'mdb/GET_POPULAR_MEDIAS_SUCCEED';
export const GET_POPULAR_MEDIAS_FAILED = 'mdb/GET_POPULAR_MEDIAS_FAILED';

export const GET_TRENDING_MEDIAS = 'mdb/GET_TRENDING_MEDIAS';
export const GET_TRENDING_MEDIAS_SUCCEED = 'mdb/GET_TRENDING_MEDIAS_SUCCEED';
export const GET_TRENDING_MEDIAS_FAILED = 'mdb/GET_TRENDING_MEDIAS_FAILED';

export const GET_CATALOG_MOVIES = 'mdb/GET_CATALOG_MOVIES';
export const GET_CATALOG_MOVIES_SUCCEED = 'mdb/GET_CATALOG_MOVIES_SUCCEED';
export const GET_CATALOG_MOVIES_FAILED = 'mdb/GET_DISCOVER_MOVIES_FAILED';

export const GET_CATALOG_TV_SHOWS = 'mdb/GET_CATALOG_TV_SHOWS';
export const GET_CATALOG_TV_SHOWS_SUCCEED = 'mdb/GET_CATALOG_TV_SHOWS_SUCCEED';
export const GET_CATALOG_TV_SHOWS_FAILED = 'mdb/GET_DISCOVER_TV_SHOWS_FAILED';
