export const GET_MOVIES = 'mdb/GET_MOVIES';
export const GET_POPULAR_MOVIES = 'mdb/GET_POPULAR_MOVIES';
export const GET_POPULAR_MOVIES_SUCCEED = 'mdb/GET_POPULAR_MOVIES_SUCCEED';
export const GET_POPULAR_MOVIES_FAILED = 'mdb/GET_POPULAR_MOVIES_FAILED';
